name: gh-alicloud

on:
    push: 
      branches: 
        - main


jobs:
  ssh:
    runs-on: ubuntu-latest  
      steps:
        - 
          run: ssh -i ${{secrets.SSH_KEY}} ${{ secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} "hostname"
          

